### ISSUE TITLE
No module named `city_of_chicago` while import neighborhoodize

### ISSUE THREAD

**Issue by CuriousLearner** [bjlange/neighborhoodize#6]
Hi,

I installed the package and tried to import it as described in the README, but it failed. Here is the traceback:

```
In [1]: import neighborhoodize                                                                                                                                                           
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-0c4a2f1d657b> in <module>
----> 1 import neighborhoodize

~/venv/lib/python3.7/site-packages/neighborhoodize/__init__.py in <module>
      5 import sys
      6 
----> 7 import city_of_chicago
      8 import nyc
      9 import zillow

ModuleNotFoundError: No module named 'city_of_chicago'
```

Can you please help?

Many thanks!

**Comment by CuriousLearner** [comment]
The module seems to be there in the package that is installed through pip. Not sure what is the issue here.

**Comment by bjlange** [comment]
Hi @CuriousLearner! At first glance I'm not sure what's going on. At the moment I don't have the time to dig into it; I may be able to later this year. If you do, and manage to put together a PR, I'd review and approve it.

One question: can you tell me about your environment? E.g. what version of python?

**Comment by bjlange** [comment]
@CuriousLearner I believe I fixed it. Latest version is up on PyPI, you should be able to `pip install --upgrade Neighborhoodize`. Should be version 0.9.6

**Comment by CuriousLearner** [comment]
Thank you so much @bjlange :) I'll give it a try soon.
